/*
 * This file is generated by jOOQ.
*/
package com.jooq.test.domain;


import com.jooq.test.domain.tables.AlpakkaSlickJavadslTestUsers;
import com.jooq.test.domain.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in test_temp
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>test_temp.alpakka_slick_javadsl_test_users</code>.
     */
    public static final AlpakkaSlickJavadslTestUsers ALPAKKA_SLICK_JAVADSL_TEST_USERS = com.jooq.test.domain.tables.AlpakkaSlickJavadslTestUsers.ALPAKKA_SLICK_JAVADSL_TEST_USERS;

    /**
     * The table <code>test_temp.user</code>.
     */
    public static final User USER = com.jooq.test.domain.tables.User.USER;
}
